mounts: /etc/fstab # or select manually:
                   # mount_at_start: "proc" "/proc" "proc" 0 ""
services: /etc/iinit.services
                   # or select manually:
                   # run_service: /bin/bash -g 
                   # wait: 1
